const ACTION_TYPES = {
    GET_CHARACTERS_PENDING : 'GET_CHARACTERS_PENDING',
    GET_CHARACTERS_SUCCESS : 'GET_CHARACTERS_SUCCESS',
    GET_CHARACTERS_FAILURE : 'GET_CHARACTERS_FAILURE',

    GET_DETAIL_CHARACTER_PENDING : 'GET_DETAIL_CHARACTER_PENDING',
    GET_DETAIL_CHARACTER_SUCCESS : 'GET_DETAIL_CHARACTER_SUCCESS',
    GET_DETAIL_CHARACTER_FAILURE : 'GET_DETAIL_CHARACTER_FAILURE',

    GET_CHARACTERS_COMICS_PENDING: 'GET_CHARACTERS_COMICS_PENDING',
    GET_CHARACTERS_COMICS_SUCCESS: 'GET_CHARACTERS_COMICS_SUCCESS',
    GET_CHARACTERS_COMICS_FAILURE: 'GET_CHARACTERS_COMICS_FAILURE'
}

export default ACTION_TYPES;